// AUTO-PORTED from CareProviderSearch.jsx — postcode/council/region engine.
// Constants below (normCouncil, COUNCIL_NORM_MAP, REGION_NORM, ASYLUM_MAP) are unchanged.

export function normCouncil(name) {
  if (!name) return "";
  let n = name.toLowerCase().trim();
  // Make "&" equivalent to " and " before any stripping, so db-side
  // "Hammersmith & Fulham" matches postcodes.io "Hammersmith and Fulham".
  n = n.replace(/&/g, " and ");
  n = n.replace(/,\s*city of$/, " city");
  // Collapse "city of london corporation" → "city of london" so the verbose
  // db-side name matches postcodes.io's admin_district "City of London".
  n = n.replace(/^city of london corporation$/, "city of london");
  // Strip the verbose London borough prefixes BEFORE the generic word strip,
  // so the db-side key "London Borough of Lewisham" reduces to "lewisham" and
  // matches the postcodes.io admin_district "Lewisham". Optional leading "the ".
  n = n.replace(/^(?:the\s+)?(?:london borough of|royal borough of)\s+/, "");
  n = n.replace(/\b(council|metropolitan borough|borough|county|district|unitary authority|mbc|lbc|the )\b/g, " ");
  // Strip "city" only when NOT inside "city of london" (which is a real
  // commissioner that we keep as a distinguishable key).
  if (n !== "city of london" && !n.startsWith("city of london ")) {
    n = n.replace(/\bcity\b/g, " ");
  }
  n = n.replace(/[^\w\s]/g, " ");
  n = n.replace(/\s+/g, " ").trim();
  return n;
}

// All council keys from DB, pre-normalised for lookup
export const COUNCIL_NORM_MAP = {
  "east riding of yorkshire": ["East Riding of Yorkshire Council","EAST RIDING OF YORKSHIRE COUNCIL",".East Riding Of Yorkshire Council"],
  "adur": ["Adur District Council"],
  "brighton hove": ["Brighton & Hove City Council","Brighton and Hove City Council","BRIGHTON & HOVE CITY COUNCIL"],
  "barnsley": ["Barnsley Metropolitan Borough Council"],
  "basingstoke deane": ["Basingstoke & Deane Borough Council","Basingstoke and Deane Borough Council"],
  "bath and north east somerset": ["Bath and North East Somerset Council"],
  "bedford": ["Bedford Borough Council"],
  "birmingham": ["Birmingham City Council"],
  "blackburn with darwen": ["Blackburn with Darwen"],
  "blackpool": ["Blackpool Council"],
  "bolton": ["Bolton Council"],
  "bradford": ["Bradford Metropolitan District Council","City of Bradford Metropolitan District Council","CITY OF BRADFORD METROPOLITAN DISTRICT COUNCIL"],
  "brighton": ["Brighton & Hove City Council","Brighton and Hove City Council"],
  "bristol": ["Bristol City Council","BRISTOL CITY COUNCIL"],
  "buckinghamshire": ["Buckinghamshire Council","Buckinghamshire County Council"],
  "bury": ["Bury Council"],
  "calderdale": ["Calderdale Council","The Borough Council of Calderdale"],
  "cambridge": ["Cambridge City Council"],
  "cambridgeshire": ["Cambridgeshire County Council"],
  "peterborough": ["Peterborough City Council","Cambridgeshire County Council and Peterborough City Council"],
  "canterbury": ["Canterbury City Council"],
  "central bedfordshire": ["Central Bedfordshire Council"],
  "cheltenham": ["Cheltenham Borough Council"],
  "cheshire east": ["Cheshire East Borough Council","CHESHIRE EAST COUNCIL"],
  "cheshire west and chester": ["Cheshire west and Chester Borough Council"],
  "colchester": ["Colchester City Council"],
  "cornwall": ["Cornwall Council","CORNWALL COUNCIL"],
  "coventry": ["Coventry City Council","Coventry City Council (COV)"],
  "cumbria": ["Cumbria County Council"],
  "darlington": ["Darlington Borough Council"],
  "derby": ["Derby City Council","DERBY CITY COUNCIL"],
  "derbyshire": ["Derbyshire County Council","DERBYSHIRE COUNTY COUNCIL"],
  "devon": ["Devon County Council"],
  "doncaster": ["City of Doncaster Council","Doncaster Council","Doncaster MBC"],
  "dorset": ["Dorset Council","Dorset County Council"],
  "dudley": ["Dudley Metropolitan Borough Council","DUDLEY MBC"],
  "durham": ["Durham County Council","DURHAM COUNTY COUNCIL"],
  "east suffolk": ["East Suffolk Council"],
  "east sussex": ["East Sussex County Council"],
  "erewash": ["Erewash Borough Council"],
  "essex": ["Essex County Council","ESSEX COUNTY COUNCIL"],
  "exeter": ["Exeter City Council"],
  "folkestone and hythe": ["Folkestone and Hythe District Council"],
  "gateshead": ["Gateshead Council","GATESHEAD COUNCIL"],
  "gloucester": ["Gloucester City Council"],
  "gloucestershire": ["Gloucestershire County Council"],
  "gosport": ["Gosport Borough Council"],
  "hampshire": ["Hampshire County Council","HAMPSHIRE COUNTY COUNCIL"],
  "halton": ["Halton Borough Council"],
  "harrow": ["Harrow Council"],
  "hartlepool": ["Hartlepool Borough Council"],
  "hastings": ["Hastings Borough Council"],
  "herefordshire": ["Herefordshire Council"],
  "hertfordshire": ["Hertfordshire County Council  - Adult Care Services","Hertfordshire County Council - Children's Services"],
  "hull": ["Hull City Council"],
  "kingston upon hull": ["Hull City Council"],
  "islington": ["Islington Council","ISLINGTON COUNCIL","Islington"],
  "ipswich": ["Ipswich Borough Council"],
  "isle of wight": ["Isle of Wight Council"],
  "kent": ["Kent County Council","KENT COUNTY COUNCIL"],
  "kirklees": ["Kirklees Council"],
  "knowsley": ["Knowsley Council"],
  "lancashire": ["Lancashire County Council"],
  "lancaster": ["Lancaster City Council"],
  "leeds": ["Leeds City Council"],
  "leicester": ["Leicester City Council"],
  "leicestershire": ["Leicestershire County Council"],
  "lincolnshire": ["Lincolnshire County Council","LINCOLNSHIRE COUNTY COUNCIL"],
  "liverpool": ["Liverpool City Council"],
  "barking and dagenham": ["London Borough of Barking and Dagenham","London Borough Of Barking And Dagenham","London Borough of Barking & Dagenham"],
  "barnet": ["London Borough of Barnet Council"],
  "bexley": ["London Borough of Bexley","London Borough Of Bexley"],
  "brent": ["London Borough of Brent"],
  "bromley": ["London Borough of Bromley","London Borough Of Bromley Council","London Borough of Bromley Council"],
  "camden": ["London Borough of Camden","London Borough of Camden Council","London Borough Of Camden Council"],
  "enfield": ["London Borough of Enfield"],
  "hackney": ["London Borough of Hackney"],
  "hammersmith and fulham": ["London Borough of Hammersmith & Fulham"],
  "haringey": ["London Borough of Haringey","London Borough Of Haringey"],
  "havering": ["London Borough of Havering","LONDON BOROUGH OF HAVERING"],
  "hillingdon": ["London Borough of Hillingdon"],
  "hounslow": ["London Borough of Hounslow","LONDON BOROUGH OF HOUNSLOW"],
  "lambeth": ["London Borough of Lambeth"],
  "lewisham": ["London Borough of Lewisham"],
  "merton": ["London Borough of Merton"],
  "redbridge": ["London Borough of Redbridge"],
  "richmond upon thames": ["London Borough of Richmond upon Thames"],
  "sutton": ["London Borough of Sutton"],
  "wandsworth": ["London Borough of Wandsworth"],
  "tower hamlets": ["Tower Hamlets","LONDON BOROUGH OF TOWER HAMLETS"],
  "city of london": ["City of London Corporation"],
  "greenwich": ["Royal Borough Of Greenwich"],
  "kingston upon thames": ["The Royal Borough of Kingston upon Thames"],
  "westminster": ["Westminster City Council"],
  "luton": ["Luton Council"],
  "manchester": ["Manchester City Council"],
  "medway": ["Medway Council"],
  "middlesbrough": ["Middlesbrough Council"],
  "milton keynes": ["Milton Keynes Council","Milton Keynes City Council"],
  "newcastle upon tyne": ["Newcastle City Council","NEWCASTLE CITY COUNCIL"],
  "norfolk": ["Norfolk County Council"],
  "north east lincolnshire": ["North East Lincolnshire Council"],
  "north hertfordshire": ["North Hertfordshire District Council"],
  "north lincolnshire": ["North Lincolnshire Council"],
  "north northamptonshire": ["North Northamptonshire Council"],
  "north somerset": ["North Somerset Council"],
  "north tyneside": ["North Tyneside Council"],
  "northamptonshire": ["Northamptonshire County Council"],
  "northumberland": ["Northumberland County Council"],
  "nottingham": ["Nottingham City Council","NOTTINGHAM CITY COUNCIL"],
  "nottinghamshire": ["Nottinghamshire County Council"],
  "oxford": ["Oxford City Council"],
  "oxfordshire": ["Oxfordshire County Council"],
  "plymouth": ["Plymouth City Council"],
  "preston": ["Preston City Council"],
  "reading": ["Reading Borough Council","READING BOROUGH COUNCIL"],
  "redcar and cleveland": ["Redcar & Cleveland Borough Council","REDCAR & CLEVELAND BOROUGH COUNCIL"],
  "redditch": ["Redditch Borough Council"],
  "rochdale": ["Rochdale Metropolitan Borough Council"],
  "rotherham": ["Rotherham Metropolitan Borough Council","Rotherham MBC"],
  "salford": ["Salford City Council"],
  "sandwell": ["Sandwell Metropolitan Borough Council","SANDWELL METROPOLITAN BOROUGH COUNCIL"],
  "sefton": ["Sefton Council"],
  "sheffield": ["Sheffield City Council"],
  "shropshire": ["Shropshire Council","SHROPSHIRE COUNCIL"],
  "solihull": ["Solihull MBC (SOL)","SOLIHULL METROPOLITAN BOROUGH COUNCIL"],
  "somerset": ["Somerset Council","Somerset County Council"],
  "south tyneside": ["South Tyneside Council"],
  "southampton": ["Southampton City Council","SOUTHAMPTON CITY COUNCIL"],
  "southend on sea": ["Southend-On-Sea Borough Council"],
  "staffordshire": ["Staffordshire County Council"],
  "stockport": ["Stockport Metropolitan Borough Council"],
  "stockton on tees": ["Stockton Borough Council"],
  "stoke on trent": ["Stoke-on-Trent City Council"],
  "sunderland": ["Sunderland City Council"],
  "tameside": ["Tameside Metropolitan Borough Council"],
  "tewkesbury": ["Tewkesbury Borough Council"],
  "thanet": ["Thanet District Council"],
  "north yorkshire": ["The North Yorkshire Council"],
  "thurrock": ["Thurrock Council","Thurrock Borough Council"],
  "torbay": ["Torbay Council","TORBAY COUNCIL"],
  "torridge": ["Torridge District Council"],
  "trafford": ["Trafford Council"],
  "wakefield": ["Wakefield Council","WAKEFIELD COUNCIL"],
  "walsall": ["Walsall Council e-Tendering"],
  "warwickshire": ["Warwickshire County Council","Warwickshire County Council (WCC)"],
  "west berkshire": ["West Berkshire Council","West Berkshire District Council"],
  "west sussex": ["West Sussex County Council (CAP)","WEST SUSSEX COUNTY COUNCIL"],
  "wigan": ["Wigan Council"],
  "wiltshire": ["Wiltshire Council"],
  "wirral": ["Wirral Borough Council"],
  "wokingham": ["Wokingham Borough Council"],
  "wolverhampton": ["Wolverhampton City Council"],
  "worcester": ["Worcester City Council"],
  "worcestershire": ["Worcestershire County Council"],
  "worthing": ["Worthing Borough Council"],
  "wyre forest": ["Wyre Forest District Council"],
  "king s lynn and west norfolk": ["Borough Council of King's Lynn & West Norfolk"],
};

// ONS region from postcodes.io region field
export const REGION_NORM = {
  "east midlands": "East Midlands",
  "east of england": "East of England",
  "london": "London",
  "north east": "North East",
  "north west": "North West",
  "south east": "South East",
  "south west": "South West",
  "west midlands": "West Midlands",
  "yorkshire and the humber": "Yorkshire & The Humber",
  "yorkshire and humber": "Yorkshire & The Humber",
};

export const ASYLUM_MAP = {
  "North East": "Mears Group",
  "Yorkshire & The Humber": "Mears Group",
  "North West": "Serco",
  "East Midlands": "Serco",
  "West Midlands": "Serco",
  "East of England": "Serco",
  "London": "Clearsprings Ready Homes",
  "South East": "Clearsprings Ready Homes",
  "South West": "Clearsprings Ready Homes",
};
